name: Build Wheels

on: [ push, pull_request ]

jobs:
  build_wheels:
    name: Build wheels ${{ matrix.CIBW_BUILD }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
#          - CIBW_BUILD: cp36-manylinux_x86_64
#            os: ubuntu-latest
#            arch: x86_64
#            CIBW_PLATFORM: linux
#          - CIBW_BUILD: cp37-manylinux_x86_64
#            os: ubuntu-latest
#            arch: x86_64
#            CIBW_PLATFORM: linux
#          - CIBW_BUILD: cp38-manylinux_x86_64
#            os: ubuntu-latest
#            arch: x86_64
#            CIBW_PLATFORM: linux
#          - CIBW_BUILD: cp39-manylinux_x86_64
#            os: ubuntu-latest
#            arch: x86_64
#            CIBW_PLATFORM: linux
#
#          - CIBW_BUILD: cp37-manylinux_aarch64
#            os: ubuntu-latest
#            arch: aarch64
#            CIBW_PLATFORM: linux
#          - CIBW_BUILD: cp38-manylinux_aarch64
#            os: ubuntu-latest
#            arch: aarch64
#            CIBW_PLATFORM: linux
#          - CIBW_BUILD: cp39-manylinux_aarch64
#            os: ubuntu-latest
#            arch: aarch64
#            CIBW_PLATFORM: linux
#
#          - CIBW_BUILD: cp36-macosx_x86_64
#            os: macos-latest
#            arch: x86_64
#            CIBW_PLATFORM: macos
#          - CIBW_BUILD: cp37-macosx_x86_64
#            os: macos-latest
#            arch: x86_64
#            CIBW_PLATFORM: macos
#          - CIBW_BUILD: cp38-macosx_x86_64
#            os: macos-latest
#            arch: x86_64
#            CIBW_PLATFORM: macos
#          - CIBW_BUILD: cp39-macosx_x86_64
#            os: macos-latest
#            arch: x86_64
#            CIBW_PLATFORM: macos
#
#          - CIBW_BUILD: cp38-macosx_arm64
#            os: macos-latest
#            arch: arm64
#            CIBW_PLATFORM: macos
#          - CIBW_BUILD: cp39-macosx_arm64
#            os: macos-latest
#            arch: arm64
#            CIBW_PLATFORM: macos

          - CIBW_BUILD: cp36-win_amd64
            os: windows-latest
            arch: AMD64
            CIBW_PLATFORM: windows
          - CIBW_BUILD: cp37-win_amd64
            os: windows-latest
            arch: AMD64
            CIBW_PLATFORM: windows
#          - CIBW_BUILD: cp38-win_amd64
#            os: windows-latest
#            arch: AMD64
#            CIBW_PLATFORM: windows
          - CIBW_BUILD: cp39-win_amd64
            os: windows-latest
            arch: AMD64
            CIBW_PLATFORM: windows

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install cibuildwheel
        run: |
          pip install wheel
          pip install -e ".[compat,dev]" cibuildwheel twine
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel numpy tox
      - name: Build wheels
        run: |
          python setup.py bdist_wheel
          cibuildwheel --output-dir dist
          ls dist
        env:
          CIBW_BUILD: ${{ matrix.CIBW_BUILD }}
          CIBW_PLATFORM: ${{ matrix.CIBW_PLATFORM }}
          CIBW_ARCHS: ${{matrix.arch}}
          CIBW_BEFORE_BUILD: "pip install cython cmake delvewheel"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel show {wheel} && delvewheel repair -w {dest_dir} {wheel}"

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl
